const BASE_URL = process.env.BASE_URL;

const GESTAODEPESSOAS = 'Gestão de Pessoas | HCM';

// ################# PAINEL DE GESTÃO #################
const PAINELGESTAO = 'Painel de gestão';
const FERIAS = 'Férias';
const FERIASDAEQUIPE = 'Férias da equipe';
const CONFIGURACOESEGERENCIAMENTO = 'Configurações e gerenciamen...';
const PAINELDOGESTOR = 'Painel do gestor';
const MEUPAINEL = 'Meu painel';
const PAINELDORH = 'Painel do RH';
const GERENCIAMENTOEAUDITORIA = 'Gerenciamento e auditoria';
const PERFIL = 'Perfil';
const PESSOAL = 'Pessoal';
const PAINELGESTOR = 'Painel do gestor';
const CONTRATOSSALARIOS = 'Contratos e salários';
const CONTRATOTRABALHO = 'Contrato de trabalho';
const CONFIGURACOESGERAIS = 'Configurações gerais';
const CONFIGURACOESGERENCIAMENTO = 'Configurações e gerenciamen...';

export const PAINELGESTAO_ADMINISTRACAOPAPEIS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, CONFIGURACOESEGERENCIAMENTO, GERENCIAMENTOEAUDITORIA, 'Administração de papéis'],
};
export const PAINELGESTAO_MINHASFERIAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, FERIAS, 'Minhas férias'],
};
export const PAINELGESTAO_CALENDARIOFERIAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, FERIAS, 'Calendário de férias da equ...'],
};
export const PAINELGESTAO_POLITICAFERIAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, CONFIGURACOESEGERENCIAMENTO, 'Política de férias'],
};
export const PAINELGESTAO_CALENDARIOEQUIPE = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDOGESTOR, FERIASDAEQUIPE, 'Calendário de férias'],
};
export const PAINELGESTAO_PROGRAMARFERIAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDOGESTOR, FERIASDAEQUIPE, 'Programar férias'],
};
export const PAINELGESTAO_FERIAPROGRAMADAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDOGESTOR, FERIASDAEQUIPE, 'Programadas'],
};
export const PAINELGESTAO_AGURDANDOAPROVACAOFERIAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDOGESTOR, FERIASDAEQUIPE, 'Aguardando aprovação'],
};
export const PAINELGESTAO_FERIASCALCULADAS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDOGESTOR, FERIASDAEQUIPE, 'Calculadas'],
};
export const PAINELGESTAO_EMABERTO = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDOGESTOR, FERIASDAEQUIPE, 'Períodos em aberto'],
};
export const PAINELGESTAO_MEUPERILPUBLICO = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, PERFIL, 'Perfil público'],
};
export const PAINELGESTAO_MEUPERFIL = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, PERFIL, PESSOAL, 'Meu perfil'],
};
export const PAINELGESTAO_PERFILACADEMICO = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, PERFIL, PESSOAL, 'Perfil acadêmico'],
};
export const PAINELGESTAO_MEUSLIDERADOS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELGESTOR, 'Meus liderados'],
};
export const PAINELGESTAO_COMPARARSALARIOEQUIPE = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELGESTOR, CONTRATOSSALARIOS, 'Comparar salários da equipe'],
};
export const PAINELGESTAO_SOLICITACOESPENDENTES = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, PAINELDORH, 'Solicitações pendentes'],
};
export const PAINELGESTAO_MEUCONTRATOTRABALHO = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, CONTRATOTRABALHO, 'Meu contrato de trabalho'],
};
export const PAINELGESTAO_OBRIGATORIEDADECOMPROVANTE = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, CONFIGURACOESGERENCIAMENTO, CONFIGURACOESGERAIS, 'Obrigatoriedade de comprova...'],
};
export const PAINELGESTAO_DEFINICOESGERAIS = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, CONFIGURACOESGERENCIAMENTO, CONFIGURACOESGERAIS, 'Definições gerais'],
};
export const PAINELGESTAO_CONFIGURACOESPRIVACIDADE = {
  URL: `${BASE_URL}`,
  DIRETORIO: [GESTAODEPESSOAS, PAINELGESTAO, MEUPAINEL, 'Configurações de privacidad...'],
};
